---
# EPEL Repo
- name: Install EPEL YUM Repo
  yum_repository:
    name: "epel"
    description: "EPEL YUM repo"
    baseurl: "http://dl.fedoraproject.org/pub/epel/$releasever/$basearch/"
    gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    gpgcheck: true
  when: nginx_repo_enabled
